name: Shell commands

on: [push]

jobs:
    run-shell-command:
        runs-on: ubuntu-18.04
        steps:
            - name: echo a string
              run: echo "Hello My world of Github Actions"
            - name: multiline script
              run: |
                node -v
                npm -v
                python -v